from .io import NODE_CLASS_MAPPINGS as IO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IO_NODE_DISPLAY_NAME_MAPPINGS
from .loader import NODE_CLASS_MAPPINGS as LOADER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOADER_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **IO_NODE_CLASS_MAPPINGS,
    **LOADER_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **IO_NODE_DISPLAY_NAME_MAPPINGS,
    **LOADER_NODE_DISPLAY_NAME_MAPPINGS,
}
